import type { MoodConfig, MoodType, GuidedPrompt } from "../types";

export const MOODS: Record<MoodType, MoodConfig> = {
  great: {
    type: "great",
    label: "Thriving & Joyful",
    emoji: "🌟",
    color: "text-amber-600 dark:text-amber-400",
    bgLight: "bg-amber-50 text-amber-900 border-amber-200",
    bgDark: "dark:bg-amber-950/40 dark:text-amber-200 dark:border-amber-800/60",
    borderColor: "border-amber-300 dark:border-amber-700",
  },
  good: {
    type: "good",
    label: "Calm & Content",
    emoji: "🌿",
    color: "text-emerald-600 dark:text-emerald-400",
    bgLight: "bg-emerald-50 text-emerald-900 border-emerald-200",
    bgDark: "dark:bg-emerald-950/40 dark:text-emerald-200 dark:border-emerald-800/60",
    borderColor: "border-emerald-300 dark:border-emerald-700",
  },
  grateful: {
    type: "grateful",
    label: "Deeply Grateful",
    emoji: "✨",
    color: "text-teal-600 dark:text-teal-400",
    bgLight: "bg-teal-50 text-teal-900 border-teal-200",
    bgDark: "dark:bg-teal-950/40 dark:text-teal-200 dark:border-teal-800/60",
    borderColor: "border-teal-300 dark:border-teal-700",
  },
  reflective: {
    type: "reflective",
    label: "Introspective",
    emoji: "🔮",
    color: "text-indigo-600 dark:text-indigo-400",
    bgLight: "bg-indigo-50 text-indigo-900 border-indigo-200",
    bgDark: "dark:bg-indigo-950/40 dark:text-indigo-200 dark:border-indigo-800/60",
    borderColor: "border-indigo-300 dark:border-indigo-700",
  },
  energized: {
    type: "energized",
    label: "Inspired & Driven",
    emoji: "⚡",
    color: "text-orange-600 dark:text-orange-400",
    bgLight: "bg-orange-50 text-orange-900 border-orange-200",
    bgDark: "dark:bg-orange-950/40 dark:text-orange-200 dark:border-orange-800/60",
    borderColor: "border-orange-300 dark:border-orange-700",
  },
  neutral: {
    type: "neutral",
    label: "Steady & Neutral",
    emoji: "☁️",
    color: "text-slate-600 dark:text-slate-400",
    bgLight: "bg-slate-50 text-slate-900 border-slate-200",
    bgDark: "dark:bg-slate-900/60 dark:text-slate-200 dark:border-slate-800",
    borderColor: "border-slate-300 dark:border-slate-700",
  },
  anxious: {
    type: "anxious",
    label: "Anxious & Uneasy",
    emoji: "🌊",
    color: "text-cyan-600 dark:text-cyan-400",
    bgLight: "bg-cyan-50 text-cyan-900 border-cyan-200",
    bgDark: "dark:bg-cyan-950/40 dark:text-cyan-200 dark:border-cyan-800/60",
    borderColor: "border-cyan-300 dark:border-cyan-700",
  },
  stressed: {
    type: "stressed",
    label: "High Pressure",
    emoji: "🔥",
    color: "text-rose-600 dark:text-rose-400",
    bgLight: "bg-rose-50 text-rose-900 border-rose-200",
    bgDark: "dark:bg-rose-950/40 dark:text-rose-200 dark:border-rose-800/60",
    borderColor: "border-rose-300 dark:border-rose-700",
  },
  sad: {
    type: "sad",
    label: "Heavyhearted / Low",
    emoji: "🌧️",
    color: "text-blue-600 dark:text-blue-400",
    bgLight: "bg-blue-50 text-blue-900 border-blue-200",
    bgDark: "dark:bg-blue-950/40 dark:text-blue-200 dark:border-blue-800/60",
    borderColor: "border-blue-300 dark:border-blue-700",
  },
};

export const DEFAULT_PROMPTS: GuidedPrompt[] = [
  {
    id: "morning-clarity",
    title: "Morning Intentions & Mindset",
    description: "Anchor your day with conscious priorities and emotional alignment.",
    prompt: "What is the single most important energy or value you wish to embody today? What is one gentle boundary you will hold for yourself?",
    estimatedMinutes: 5,
    moodCategory: "Morning Flow",
  },
  {
    id: "evening-release",
    title: "Evening Unwind & Decompression",
    description: "Let go of what you cannot control and celebrate small micro-victories.",
    prompt: "What drained your energy today, and what can you consciously release before sleeping? What was one unexpected moment of delight or relief?",
    estimatedMinutes: 10,
    moodCategory: "Evening Reflection",
  },
  {
    id: "gratitude-deep-dive",
    title: "3 Unconventional Gratitudes",
    description: "Notice the subtle, overlooked gifts in your daily surroundings.",
    prompt: "Write about three tiny, specific sensory things you are grateful for today (a taste, a warmth, a kind word, or a silent pause). Why did they matter?",
    estimatedMinutes: 5,
    moodCategory: "Gratitude",
  },
  {
    id: "overcoming-fog",
    title: "Unpacking Overwhelm",
    description: "Transform internal chaos into structured clarity.",
    prompt: "Dump everything swirling in your head right now. Next, separate what is within your direct sphere of control versus what you must surrender.",
    estimatedMinutes: 12,
    moodCategory: "Clarity",
  },
  {
    id: "future-self",
    title: "Wisdom From Your Future Self",
    description: "Gain perspective by zooming out 5 years into the future.",
    prompt: "If your wiser, grounded future self from 5 years ahead could whisper advice to you regarding your current challenge, what would they say?",
    estimatedMinutes: 8,
    moodCategory: "Perspective",
  },
];

export const POPULAR_TAGS = [
  "Mindfulness",
  "Gratitude",
  "Career",
  "Relationships",
  "Health & Body",
  "Creativity",
  "Personal Growth",
  "Emotional Processing",
  "Family",
  "Habits",
  "Decision Making",
];
